package com.example.higherorlower;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import java.util.Random;

public class MainActivity extends AppCompatActivity {
    int num;
    Random rand=new Random();

    public void generateRandomNumber(){
        num=rand.nextInt(20)+1;

    }
    public void guess(View view){

       EditText editText=(EditText)findViewById(R.id.editTextNumber);
       int guessValue= Integer.parseInt(editText.getText().toString());
       String message;
       if (guessValue>num){
           message="Lower";
       }else if (guessValue<num){
           message="Higher";
       }else {
           message="You are correct. Wanna play again";
           generateRandomNumber();
       }
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
       Log.i("User Input", editText.getText().toString());
       Log.i("Info", Integer.toString(num));// this code shows the random number generated by the program.

    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Random rand=new Random();
        num=rand.nextInt(20)+1;
    }
}